name: "I have issues"

description: "consume the output of the previous action and create a new issue in the repo"

inputs:
  joke:
    description: "body of created issue"
  issue-title: 
    description: "default title "
    default: "a joke for you"
    required: true
  repo-token:
    description: "Token with permission to do repo things"


runs:
  using: "node12"
  main: "index.js"
