name: JS Actions

on:
  pull_request:
    types: [labeled]

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      
      - name: "hello-action"
        uses: ./.github/actions/hello-world

      - name: ha-ha
        uses: ./.github/actions/joke-action
        
